spring:
  banner:
    location: banner.txt
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_IP}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
        ddl-auto: create-drop
    generate-ddl: true

application:
  title: find-the-store
  version: 1.0.0